// <auto-generated />
using System;
using EmployeeManagementSystem.Blazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementSystem.Blazor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241110173501_CreateEmployeeTable")]
    partial class CreateEmployeeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementSystem.Blazor.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EmployeeManagementSystem.Blazor.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobTitle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14f0f612-6b2b-71d2-0c1c-48d1422eafcd"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/2638945",
                            JobTitle = 5,
                            Name = "Maeve Dickens",
                            Salary = 32942.968845806540000m
                        },
                        new
                        {
                            Id = new Guid("acafa487-4f63-39d9-cd37-865118d63b35"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/8075100",
                            JobTitle = 1,
                            Name = "Montana Nitzsche",
                            Salary = 144824.450409423740000m
                        },
                        new
                        {
                            Id = new Guid("3bf6bb35-68d2-2f8b-e298-d3616e4c647e"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/84756549",
                            JobTitle = 5,
                            Name = "Dasia Moen",
                            Salary = 52551.327763382060000m
                        },
                        new
                        {
                            Id = new Guid("d916f14a-2f91-2a13-9113-c5126ff4b527"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/28423627",
                            JobTitle = 4,
                            Name = "Deontae Leuschke",
                            Salary = 114647.187169011260000m
                        },
                        new
                        {
                            Id = new Guid("ef67b77e-44d0-fc94-6c18-2624700525f8"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/55723525",
                            JobTitle = 7,
                            Name = "Sydney Quigley",
                            Salary = 28499.034572625080000m
                        },
                        new
                        {
                            Id = new Guid("70dd5c9b-e0c9-2705-25b0-bb5d725e71a2"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/97972102",
                            JobTitle = 2,
                            Name = "Julius Kohler",
                            Salary = 112904.136792246260000m
                        },
                        new
                        {
                            Id = new Guid("af834aec-8402-5099-829d-e6be1c0b1260"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/12324583",
                            JobTitle = 6,
                            Name = "Rafaela Wilderman",
                            Salary = 115985.516177483660000m
                        },
                        new
                        {
                            Id = new Guid("c6921369-3486-4dfe-2271-19ee6f92ec19"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/68531746",
                            JobTitle = 3,
                            Name = "Ilene Waters",
                            Salary = 77466.861008418260000m
                        },
                        new
                        {
                            Id = new Guid("6642b476-fe90-e252-9e60-ba76e0701d3b"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/39918760",
                            JobTitle = 5,
                            Name = "Kirsten Hayes",
                            Salary = 177404.131636677380000m
                        },
                        new
                        {
                            Id = new Guid("7f9b2ea4-6273-76d5-b71d-484a9cde841f"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/43897044",
                            JobTitle = 6,
                            Name = "Monserrate Ward",
                            Salary = 27230.9404645259120000m
                        },
                        new
                        {
                            Id = new Guid("7bb1f933-a3fc-2883-82f7-a3000f14cb11"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/51689363",
                            JobTitle = 2,
                            Name = "Jabari Casper",
                            Salary = 56142.362149498640000m
                        },
                        new
                        {
                            Id = new Guid("3ed3962e-ddb7-52c1-3b3a-a2ecfaa2cdf8"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/83780396",
                            JobTitle = 5,
                            Name = "Everette Donnelly",
                            Salary = 110458.948719528920000m
                        },
                        new
                        {
                            Id = new Guid("6fcf9ba7-9254-0a75-33aa-0f96ca1ba7bd"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/73435073",
                            JobTitle = 4,
                            Name = "Christopher Rosenbaum",
                            Salary = 101059.622057275760000m
                        },
                        new
                        {
                            Id = new Guid("291a235e-9244-da89-3519-02ddee386f47"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/99325548",
                            JobTitle = 1,
                            Name = "Chad Herman",
                            Salary = 41757.74032331900000m
                        },
                        new
                        {
                            Id = new Guid("b1d764dc-a850-4d46-2869-943e3dac542b"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/53389472",
                            JobTitle = 2,
                            Name = "Shaniya Barrows",
                            Salary = 56914.992656984900000m
                        },
                        new
                        {
                            Id = new Guid("6f2dec93-a44e-371c-538b-616546b55193"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/30513961",
                            JobTitle = 7,
                            Name = "Elissa Beahan",
                            Salary = 70844.059386683660000m
                        },
                        new
                        {
                            Id = new Guid("c3faaf49-5ef3-f9e1-b0ae-82e6d1ea83e0"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/49628153",
                            JobTitle = 2,
                            Name = "Kameron Schroeder",
                            Salary = 89407.435622721680000m
                        },
                        new
                        {
                            Id = new Guid("9f65d7dd-bad9-9fa0-c48c-05faa37d758a"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/91199534",
                            JobTitle = 7,
                            Name = "Audra Kuhic",
                            Salary = 108808.420053128420000m
                        },
                        new
                        {
                            Id = new Guid("66e460e3-610f-f286-b7ff-8240d1225e54"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/23580114",
                            JobTitle = 8,
                            Name = "Orpha Rutherford",
                            Salary = 38066.009524309100000m
                        },
                        new
                        {
                            Id = new Guid("0647d6e0-cf6a-72f0-9bbd-2e2bf404ba72"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/97899522",
                            JobTitle = 2,
                            Name = "Jaylon Robel",
                            Salary = 93158.212654831880000m
                        },
                        new
                        {
                            Id = new Guid("53ab6278-5c2c-2f39-00c9-c9ed800e1f08"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/77360452",
                            JobTitle = 2,
                            Name = "Dorthy Satterfield",
                            Salary = 159379.795677671120000m
                        },
                        new
                        {
                            Id = new Guid("592da611-1299-1a7b-f816-20da5ee45a17"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/30653491",
                            JobTitle = 3,
                            Name = "Trevor Reichel",
                            Salary = 80307.440301546560000m
                        },
                        new
                        {
                            Id = new Guid("ab840761-a253-6247-d08f-a2b2510425d3"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/84806153",
                            JobTitle = 5,
                            Name = "Aurelie Jacobs",
                            Salary = 157154.004758761220000m
                        },
                        new
                        {
                            Id = new Guid("3ab0a5cc-dfad-6e13-0df7-08ac4525d4ee"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/3092000",
                            JobTitle = 2,
                            Name = "Trace Lesch",
                            Salary = 185915.775944439560000m
                        },
                        new
                        {
                            Id = new Guid("5693ab37-cff1-10d0-b8d7-94ae3bdefb19"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/35914091",
                            JobTitle = 0,
                            Name = "Taya Parker",
                            Salary = 124381.66967797160000m
                        },
                        new
                        {
                            Id = new Guid("ffbfa5aa-d5ff-db68-123b-6c3b6e04a657"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/42667110",
                            JobTitle = 4,
                            Name = "Thelma Kulas",
                            Salary = 120956.372926457060000m
                        },
                        new
                        {
                            Id = new Guid("f5ea9617-a5f2-6be3-47e3-0f8c00ed96f2"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/44125326",
                            JobTitle = 7,
                            Name = "Catherine Moore",
                            Salary = 51176.320971537440000m
                        },
                        new
                        {
                            Id = new Guid("f6700042-9d72-0979-c585-6b798d281409"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/69451499",
                            JobTitle = 5,
                            Name = "Leatha Mraz",
                            Salary = 88562.898360454880000m
                        },
                        new
                        {
                            Id = new Guid("b904e12b-fbc0-a174-5461-6dbf53ea84fb"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/59063076",
                            JobTitle = 8,
                            Name = "Mikayla Jacobi",
                            Salary = 145052.378580464300000m
                        },
                        new
                        {
                            Id = new Guid("6d608720-c6dd-e519-e51c-65b9d48ff2b8"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/54448862",
                            JobTitle = 1,
                            Name = "Eloise Ankunding",
                            Salary = 80824.413877364360000m
                        },
                        new
                        {
                            Id = new Guid("2ad4ce0b-e685-b18e-b5b6-6aa1c07c5853"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/80657846",
                            JobTitle = 2,
                            Name = "Keara Stroman",
                            Salary = 73946.377939519640000m
                        },
                        new
                        {
                            Id = new Guid("f516995a-7a09-736a-a8fb-58167b9198b2"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/91566007",
                            JobTitle = 8,
                            Name = "Idell Bradtke",
                            Salary = 52776.169382397080000m
                        },
                        new
                        {
                            Id = new Guid("75ce324f-8960-e75f-9ac2-8dbb743a148f"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/20634297",
                            JobTitle = 7,
                            Name = "Martine Denesik",
                            Salary = 58417.049235858500000m
                        },
                        new
                        {
                            Id = new Guid("c700aa48-6bba-566c-1748-e9ab4ae32693"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/12132621",
                            JobTitle = 6,
                            Name = "London Schmidt",
                            Salary = 105370.416084942560000m
                        },
                        new
                        {
                            Id = new Guid("5d1dc088-b19e-4254-ec24-a0e1e9247598"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/24734431",
                            JobTitle = 5,
                            Name = "Colleen Nikolaus",
                            Salary = 168578.09873697260000m
                        },
                        new
                        {
                            Id = new Guid("30f0c9d2-4a68-66f9-2e4d-0eb32140aa5c"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/29401469",
                            JobTitle = 2,
                            Name = "Hazel McCullough",
                            Salary = 137691.401186255420000m
                        },
                        new
                        {
                            Id = new Guid("02f9690a-811e-2011-451c-ea43ee536d6d"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/17587903",
                            JobTitle = 4,
                            Name = "Cordia Aufderhar",
                            Salary = 122600.771739427340000m
                        },
                        new
                        {
                            Id = new Guid("340236d2-73ee-c026-41d6-ea0ebf873765"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/80655746",
                            JobTitle = 2,
                            Name = "Ethan Sawayn",
                            Salary = 129933.062740570520000m
                        },
                        new
                        {
                            Id = new Guid("5652dec9-5fef-f871-8bd4-cdb696c300e9"),
                            EmployeeType = 0,
                            ImageUrl = "https://avatars.githubusercontent.com/u/25945246",
                            JobTitle = 2,
                            Name = "Terence Lubowitz",
                            Salary = 121288.119936961700000m
                        },
                        new
                        {
                            Id = new Guid("e594e058-e336-d1dd-31e9-4be16d24e298"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/28931204",
                            JobTitle = 7,
                            Name = "Tracey Feest",
                            Salary = 66447.798193640900000m
                        },
                        new
                        {
                            Id = new Guid("74f10840-4365-b6e4-1383-15b58572c109"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/58847393",
                            JobTitle = 2,
                            Name = "Shanon Altenwerth",
                            Salary = 35326.0291625401160000m
                        },
                        new
                        {
                            Id = new Guid("dc55b46b-fa06-341a-3592-c7429f8cf3c1"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/52631914",
                            JobTitle = 5,
                            Name = "Nathen Kris",
                            Salary = 111202.455382422680000m
                        },
                        new
                        {
                            Id = new Guid("709eb7cb-7ad7-c19c-2e91-725c9c3c1e89"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/64138193",
                            JobTitle = 8,
                            Name = "Mossie Reinger",
                            Salary = 78392.095211144540000m
                        },
                        new
                        {
                            Id = new Guid("34d243ed-6716-8010-cd27-0ea3e99e3e96"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/67682405",
                            JobTitle = 3,
                            Name = "Lilly McGlynn",
                            Salary = 199031.753725852700000m
                        },
                        new
                        {
                            Id = new Guid("b6ef43cf-f4a3-015d-dff6-7947c95b9da2"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/1420506",
                            JobTitle = 5,
                            Name = "Monte Jacobs",
                            Salary = 120846.674768648420000m
                        },
                        new
                        {
                            Id = new Guid("8053f94d-a64b-fbc8-47da-20b7738f455f"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/36281122",
                            JobTitle = 8,
                            Name = "Jeffery Wiegand",
                            Salary = 156397.383602521040000m
                        },
                        new
                        {
                            Id = new Guid("e3d4a12a-7ff8-633c-c2b4-7284f5f66223"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/69798401",
                            JobTitle = 6,
                            Name = "Toby Bergstrom",
                            Salary = 165835.585699340060000m
                        },
                        new
                        {
                            Id = new Guid("0ee71227-045d-956f-8cf8-0435ceb2ac68"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/19835731",
                            JobTitle = 6,
                            Name = "Ernestina Crona",
                            Salary = 86951.432296517960000m
                        },
                        new
                        {
                            Id = new Guid("4f99ee44-a1fc-6b73-9262-698b7ac2fbea"),
                            EmployeeType = 1,
                            ImageUrl = "https://avatars.githubusercontent.com/u/36305665",
                            JobTitle = 5,
                            Name = "Mariana Reynolds",
                            Salary = 185104.66722077900000m
                        },
                        new
                        {
                            Id = new Guid("b027bf80-4076-f108-26ca-87bbcdf8740e"),
                            EmployeeType = 2,
                            ImageUrl = "https://avatars.githubusercontent.com/u/4193283",
                            JobTitle = 3,
                            Name = "Jaime Klocko",
                            Salary = 182065.401450761240000m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EmployeeManagementSystem.Blazor.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EmployeeManagementSystem.Blazor.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeManagementSystem.Blazor.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EmployeeManagementSystem.Blazor.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
